### ISSUE TITLE
[FE] 라벨 편집이 이슈 목록 페이지에 반영이 안 되는 버그

### ISSUE THREAD

**Issue by deprecated-hongbiii** [kyupid/issue-tracker#107]
🐛 버그 발생 상황
1. 라벨 페이지에서 라벨을 편집한다.
2. 로고 영역을 클릭해서 이슈 목록 페이지로 이동한다.
3. 짜잔~ 변경된 라벨이 화면 상에 반영이 안 되어 있습니다~
4. 물론 새로고침을 하면 반영이 되긴 한다.

**Comment by wade3420** [comment]
store 에있는 issuesQuery 에 labelUpdateAtom 를 get 으로 구독시켜주면 해결됩니다
