### ISSUE TITLE
[FE] 이슈 목록 페이지 - 열린이슈/닫힌이슈 명확하게 표시

### ISSUE THREAD

**Issue by deprecated-hongbiii** [kyupid/issue-tracker#48]
선택된 탭을 명확하게 표시하자요 (css...)

**Comment by wade3420** [comment]
이슈 부분은 수정 완료했습니다 (atom에 선언한 issueState 에 true false 에 따라서 탭의 css 를 바뀌게 했습니다_) 나머지도 그렇게 하면 될듯합니다. 
https://github.com/kyu-kim-kr/issue-tracker/pull/78
