### ISSUE TITLE
[FE] IssuesPage -> Wrapper -> Issues 이게 좀 이상함

### ISSUE THREAD

**Issue by deprecated-hongbiii** [kyupid/issue-tracker#49]
IssuesPage에서 렌더링되는 Wrapper라는 컴포넌트는 사실 Issues 컴포넌트인데
헷갈려서 Wrapper 라는 이름을 바꿔야 할 것 같습니다.

**Comment by wade3420** [comment]
공통 스타일 컴퍼넌트라 생각해서 Wrapper 라고 이름 지었습니다. 그렇지만 뜬금없긴하네요
