### ISSUE TITLE
[FE] 이슈 목록 페이지 UI 작업

### ISSUE THREAD

**Issue by deprecated-hongbiii** [kyupid/issue-tracker#9]
- [x] Header
- [x] Navbar
- [x] Wrapper

**Comment by deprecated-hongbiii** [comment]
`이슈 작성` 버튼에 hover 하면 material ui의 기본 스타일인 회색이 적용되는데, :hover 으로 색깔을 바꾸려 해도 바꿔지지가 않음

**Comment by wade3420** [comment]
popup state api 보다 useState 로  memu 를 열고 닫는게 더 좋은 것 같아서 리팩토링해보았습니다. 
```
anchorOrigin={{
          vertical: 'bottom',
          horizontal: 'left',
        }}
        transformOrigin={{
          vertical: 'top',
          horizontal: 'left',
        }}

```
메뉴 porps 에 위에 걸 추가해주면 버튼 아래로 팝업이 뜹니다. 

- `warning : findDOMNode is deprecated in StrictMode.` 해결 
- ref 로 root 컴포넌트를 내려줘야함
- 참고 자료 : findDOMNode is deprecated in StrictMode.

**Comment by wade3420** [comment]
> `이슈 작성` 버튼에 hover 하면 material ui의 기본 스타일인 회색이 적용되는데, :hover 으로 색깔을 바꾸려 해도 바꿔지지가 않음

stlyed component 에서 .MuiButton-contained:hover 에 background-color 를 줘보세염
